fieldLayouts:
  d2ae3635-d14a-4112-967e-e627cf2126c6:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 19ace75a-2492-451c-bdca-2ca29388d508
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 292e6d57-4630-4195-baf6-130290e26951 # Rich Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 411c6622-67fc-4721-bd0b-309e79c75b53
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: dd085bc3-6405-4b54-8f06-445e0bd490f7
        userCondition: null
handle: generalPages
hasTitleField: true
name: 'General Pages'
section: 23b1cfa0-851d-451e-9a21-d30b19c9d28c # General Pages
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
