fieldLayouts:
  f4be2bfc-af08-449f-80e7-cf4b81650e8e:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: edf4187f-fcc5-4428-8070-f7fa11b0fa31
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 0b7c0409-b2e2-4e94-9c4f-99c7fbdccd52
        userCondition: null
handle: storiesListing
hasTitleField: true
name: 'Stories Listing'
section: 498141fa-b1e5-43be-a5fd-bc8505d5c635 # Stories Listing
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
