columnSuffix: jjhaajpi
contentColumnType: text
fieldGroup: 511d6ba3-7eee-47b7-8eb9-c2525fcf0e0d # Home Page
handle: heroTitle
instructions: null
name: 'Hero Title'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
