columnSuffix: null
contentColumnType: string
fieldGroup: 71ea1c28-b9da-4db1-acea-ed17968c75a7 # Common
handle: photos
instructions: null
name: Photos
searchable: false
settings:
  allowSelfRelations: false
  allowSubfolders: false
  allowUploads: true
  allowedKinds:
    - image
  branchLimit: null
  defaultUploadLocationSource: 'volume:81f92cc9-472a-4040-bad6-9813606aee7b' # Uploads
  defaultUploadLocationSubpath: null
  localizeRelations: false
  maintainHierarchy: false
  maxRelations: null
  minRelations: null
  previewMode: full
  restrictFiles: true
  restrictLocation: false
  restrictedDefaultUploadSubpath: null
  restrictedLocationSource: 'volume:81f92cc9-472a-4040-bad6-9813606aee7b' # Uploads
  restrictedLocationSubpath: null
  selectionLabel: 'Add a photo'
  showSiteMenu: false
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  sources:
    - 'volume:81f92cc9-472a-4040-bad6-9813606aee7b' # Uploads
  targetSiteId: null
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
