fieldLayouts:
  7cfef680-4fc5-4655-bb65-2f57797ebeae:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: ae85047d-7e89-41d4-97f0-92cf8d37e0c0 # Nav Links
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6dc8f344-8273-49bf-a6ab-371c2d6640f3
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 72c5a0e0-9888-4c1b-a268-c62d07058b05
        userCondition: null
handle: header
name: Header
sortOrder: 1
